### ISSUE TITLE
NameError: global name 'Global' is not defined

### ISSUE THREAD

**Issue by qrkourier** [gluster/gdeploy#221]
I ran `sudo ANSIBLE_LIBRARY=:/root/gdeploy/modules/ GDEPLOY_TEMPLATES=/root/gdeploy gdeploy -vv --trace -c /root/gdeploy-ovirt-gluster.conf` on the tip of master.

```
$ git show
commit 1a172b2389a34757782be7ec23e75845de02a3df
Merge: c492ae0 2ef8204
Author: Sachidananda Urs <sacchi@gmail.com>
Date:   Thu Nov 17 20:56:22 2016 +0530
    Merge pull request #219 from gluster-deploy/master
    Do not disable stat-prefetch as part of samba setup
```

<...snip...>
```
TASK [Reloads the firewall] ****************************************************
task path: /tmp/tmpO2H0K5/firewalld-ports-op.yml:15
changed: [hyp006.example.com] => {"changed": true, "cmd": "firewall-cmd --reload", "delta": "0:00:01.005358", "end": "2016-11-18 13:00:56.112375", "rc": 0, "start": "2016-11-18 13:00:55.107017", "stderr": "", "stdout": "success", "stdout_lines": ["success"], "warnings": []}
changed: [hyp004.example.com] => {"changed": true, "cmd": "firewall-cmd --reload", "delta": "0:00:01.696034", "end": "2016-11-18 13:00:56.423115", "rc": 0, "start": "2016-11-18 13:00:54.727081", "stderr": "", "stdout": "success", "stdout_lines": ["success"], "warnings": []}
changed: [hyp005.example.com] => {"changed": true, "cmd": "firewall-cmd --reload", "delta": "0:00:01.080811", "end": "2016-11-18 13:00:56.196850", "rc": 0, "start": "2016-11-18 13:00:55.116039", "stderr": "", "stdout": "success", "stdout_lines": ["success"], "warnings": []}

PLAY RECAP *********************************************************************
hyp004.example.com : ok=3    changed=1    unreachable=0    failed=0   
hyp005.example.com : ok=3    changed=1    unreachable=0    failed=0   
hyp006.example.com : ok=3    changed=1    unreachable=0    failed=0   

Traceback (most recent call last):
  File "/bin/gdeploy", line 5, in <module>
    pkg_resources.run_script('gdeploy==2.0.1', 'gdeploy')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/EGG-INFO/scripts/gdeploy", line 228, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/EGG-INFO/scripts/gdeploy", line 207, in main
    call_features()
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeploylib/call_features.py", line 36, in call_features
    map(get_feature_dir, Global.sections)
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeploylib/call_features.py", line 83, in get_feature_dir
    section_dict, yml = feature_call(section_dict)
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeployfeatures/script/script.py", line 36, in script_execute
    if Global.trace:
NameError: global name 'Global' is not defined
```

**Comment by sac** [comment]
Ken, this commit has caused the error https://github.com/gluster/gdeploy/commit/97bf447b5b5511c

Importing Global has been missed out. I'll fix this. Thanks for reporting.

**Comment by sac** [comment]
Fixed the issue. Imported Global.

**Comment by pkchuyen** [comment]
Looks like this issue is not fixed yet.

I tried to deploy gluster with gdeploy and faced the same issue 

```
# gdeploy -vv --trace -c ovirt-gluster.conf
Traceback (most recent call last):
  File "/bin/gdeploy", line 228, in <module>
    main(sys.argv[1:])
  File "/bin/gdeploy", line 207, in main
    call_features()
  File "/usr/lib/python2.7/site-packages/gdeploylib/call_features.py", line 36, in call_features
    map(get_feature_dir, Global.sections)
  File "/usr/lib/python2.7/site-packages/gdeploylib/call_features.py", line 83, in get_feature_dir
    section_dict, yml = feature_call(section_dict)
  File "/usr/lib/python2.7/site-packages/gdeployfeatures/script/script.py", line 10, in script_execute
    Global.ignore_errors = section_dict.get('ignore_script_errors')
NameError: global name 'Global' is not defined
```

Here is the list of packages installed on my CentOS machine:

```
[root@ovirt1 username]# python --version
Python 2.7.5
[root@ovirt1 username]# rpm -qa|egrep 'gde|ansible'
ovirt-engine-hosts-ansible-inventory-4.1.0.4-1.el7.centos.noarch
gdeploy-2.0.1-9.noarch
ansible-2.2.1.0-1.el7.noarch
```

Or might I know what am i missing for this setup?
Please advice.

**Comment by sac** [comment]
Hi @pkchuyen this was fixed in later releases. gluster.org is not updated yet. Meanwhile you can update your RPM from: http://thegaul.org/builds/CentOS/

**Comment by pkchuyen** [comment]
Hi @sac 
It now works perfectly on my end with your suggestion.
Thanks a lot.
